#!/usr/bin/env bash
# PreToolUse: block Write/Edit/MultiEdit to existing files in data/.
#
# Consequence-if-violated justification (from claude_md_audit.md, Rule 2):
# Three systems load from data/ at startup — the Python Flask server, the Go API
# (platform/api/), and the ML pipeline. Modifying an existing source file corrupts
# all three silently; advisory text in CLAUDE.md cannot prevent a Write tool call.
#
# This includes data/predictions.csv (generated by intelligence/generate_predictions.ipynb
# in Task 6 and now a committed artifact). To update predictions, re-run the notebook —
# never edit predictions.csv directly.
#
# New files not yet on disk are allowed (the -f test only blocks existing files).
#
# Blocking mechanism: exit 0 with permissionDecision "deny" in hookSpecificOutput,
# which produces a structured user-facing message rather than a raw stderr dump.

input=$(cat)
file_path=$(echo "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

[[ -z "$file_path" ]] && exit 0

# Resolve to absolute path so relative paths from any working directory match.
if [[ "$file_path" = /* ]]; then
    abs_path="$file_path"
else
    abs_path="${CLAUDE_PROJECT_DIR}/${file_path}"
fi

data_dir="${CLAUDE_PROJECT_DIR}/data"

# Block only if the file already exists inside data/
if [[ "$abs_path" == "$data_dir/"* ]] && [[ -f "$abs_path" ]]; then
    jq -n --arg path "$abs_path" '{
        hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: ("READ-ONLY: \($path) is protected. Source datasets are loaded at startup by the Flask server, Go API, and ML pipeline — modifying them corrupts all three. data/predictions.csv is a generated artifact; to update it, re-run intelligence/generate_predictions.ipynb.")
        }
    }'
    exit 0
fi

exit 0
